### ISSUE TITLE
Packet Handling Failure on searching for Tetra's Forged Platform Block

### ISSUE THREAD

**Issue by FranFkntastic** [0Templ/TravelersCompass#2]
Forge 1.20.1

Tetra 6.2.0
Travelers Compass 2.0.4.2

Dragged Tetra forged wall in from *REI* panel into the travelers compass, and on beginning to scan client is disconnected from the server citing a packet handling failure in the console log.
[latest.log](https://github.com/user-attachments/files/15981955/latest.log)

**Comment by 0Templ** [comment]
> Forge 1.20.1
> 
> Tetra 6.2.0 Travelers Compass 2.0.4.2
> 
> Dragged Tetra forged wall in from _REI_ panel into the travelers compass, and on beginning to scan client is disconnected from the server citing a packet handling failure in the console log. [latest.log](https://github.com/user-attachments/files/15981955/latest.log)

The error occurs due to scanning blocks from the Tetra mod as a containers. Apparently, it involves a multiblock structure.

Unfortunately, the code for the Tetra mod for version 1.20.1 is currently unavailable, so I can't say for sure which specific block is causing the problem.

In any case, try updating Traveler's Compass to the latest version [(3.0.4)](https://legacy.curseforge.com/minecraft/mc-mods/travelers-compass/files/5474476), as older versions contained errors related to network code and search methods.

**Comment by FranFkntastic** [comment]
> > Forge 1.20.1
> > Tetra 6.2.0 Travelers Compass 2.0.4.2
> > Dragged Tetra forged wall in from _REI_ panel into the travelers compass, and on beginning to scan client is disconnected from the server citing a packet handling failure in the console log. [latest.log](https://github.com/user-attachments/files/15981955/latest.log)
> 
> The error occurs due to scanning blocks from the Tetra mod as a containers. Apparently, it involves a multiblock structure.
> 
> Unfortunately, the code for the Tetra mod for version 1.20.1 is currently unavailable, so I can't say for sure which specific block is causing the problem.
> 
> In any case, try updating Traveler's Compass to the latest version [(3.0.4)](https://legacy.curseforge.com/minecraft/mc-mods/travelers-compass/files/5474476), as older versions contained errors related to network code and search methods.

Oh, sweet, didn't realize there was an update. I'll update and try to recreate the original kick loop to see if it fixes it.
